sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t udemy-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true udemy-docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "udemy-docker-react"
  env: "Udemydockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-398800509733"
  bucket_path: "udemy-docker-react"
  on:
    branch: main    
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY